# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd11c770e9303ac376ed6b15ad7e8f54926fbb9868facd5dafe71a4a1d4422f6d9885b6ee3d549892585363d26afbc4bb3f6fac295507be47ac27574c798e41

test:
  secret_key_base: 5cf055f9e08fa02218cfdc4be0bfbcde513e9c025d805fa9c5499e38f04e7140d43ab601dba5694a53bbe0d1deb240e240ae86b9723dfe1278936d840a440d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
